name: Update Fork

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          repository: <your-username>/safety

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/pyupio/safety.git
          git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes
        run: git push origin main

